/* eslint-disable prettier/prettier */
import * as mongoose from 'mongoose';

export const ProductSchema = new mongoose.Schema({
  // id is automatically generated by mongoose
  title: {
    // mongoose uses JS types, so caps
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  }
});

// along with our defined attributes, extend the 
// defaultly available mongoose Document attributes
export interface Product extends mongoose.Document {
  id: string,
  title: string,
  description: string,
  price: number,
}